// Hand-written type declarations (see index.js for why these aren't
// generated by `napi build` in this first pass).

export class SafeguardError extends Error {
  kind: string;
  details: string;
  constructor(kind: string, details: string);
}

export interface CompareOptions {
  explain?: boolean;
  strict?: boolean;
  contract?: string;
  suppressionsToml?: string;
  oldStorageSchema?: string;
  oldStorageSchemaFormat?: string;
  newStorageSchema?: string;
  newStorageSchemaFormat?: string;
}

/**
 * The report shape matches the CLI's `--format json` output
 * (`soroban_upgrade_safeguard::render::RenderableReport` on the Rust
 * side); see the main repository's `print-schema` CLI subcommand for the
 * full JSON Schema.
 */
export type SafeguardReport = Record<string, unknown>;

export function compareBytes(
  oldWasm: Buffer,
  newWasm: Buffer,
  options?: CompareOptions | null,
): SafeguardReport;

export function compareFiles(
  oldPath: string,
  newPath: string,
  options?: CompareOptions | null,
): SafeguardReport;

export function engineVersion(): string;
