//! Inter-contract dependency model for cross-contract propagation of breaking changes.
//!
//! In a multi-contract protocol (token + pool + router + factory), a breaking change
//! in one contract's exported interface causes a runtime failure in every contract
//! that calls it — because those callers were compiled against the old interface and
//! do not re-verify it at deploy time.
//!
//! This module provides:
//!
//! - [`ContractDependency`]: a declared edge `caller → callee` with the function names
//!   the caller relies on (or empty, meaning "depends on the whole interface").
//! - [`DependencyGraph`]: the full set of edges with cycle detection and transitive
//!   propagation of breaking changes across contract boundaries.
//! - [`CrossContractFinding`]: a finding that identifies both the changed callee and
//!   the affected caller so it composes into the batch verdict.
//!
//! # Declaration format
//!
//! Dependencies are declared in the batch manifest alongside the contract pairs:
//!
//! ```toml
//! [[pairs]]
//! old  = "token_v1.wasm"
//! new  = "token_v2.wasm"
//! name = "token"
//!
//! [[pairs]]
//! old  = "pool_v1.wasm"
//! new  = "pool_v2.wasm"
//! name = "pool"
//!
//! [[dependencies]]
//! caller   = "pool"            # contract name in [[pairs]]
//! callee   = "token"           # contract name in [[pairs]]
//! functions = ["transfer", "balance"]  # optional; empty means all
//! ```
//!
//! A dependency on a contract absent from the batch is reported as a finding
//! rather than silently ignored, because the safety of the caller cannot be
//! verified without the callee.

use std::collections::{BTreeMap, BTreeSet, HashMap, HashSet, VecDeque};

use serde::{Deserialize, Serialize};

use crate::diff::{Finding, Severity};

// ── Declaration types ────────────────────────────────────────────────────────

/// A single declared dependency from `caller` to `callee`.
///
/// `functions` lists the specific function names the caller uses. When empty
/// (the default), the dependency is on the whole exported interface of the
/// callee — any caller-visible breaking change propagates.
#[derive(Debug, Clone, Deserialize, Serialize, PartialEq, Eq)]
pub struct ContractDependency {
    /// Name of the contract that makes calls (must match a `name` in `[[pairs]]`).
    pub caller: String,
    /// Name of the contract being called (must match a `name` in `[[pairs]]`).
    pub callee: String,
    /// Specific functions the caller relies on. Empty means all functions.
    #[serde(default)]
    pub functions: Vec<String>,
}

// ── Cross-contract finding ───────────────────────────────────────────────────

/// A finding generated by cross-contract propagation.
///
/// It wraps the original finding from the callee's analysis and adds the names
/// of both contracts so the batch report can show "contract B is affected by a
/// breaking change in contract A".
#[derive(Debug, Clone, Serialize)]
pub struct CrossContractFinding {
    /// The contract whose interface broke (the callee).
    pub changed_contract: String,
    /// The contract that depends on the broken interface (the caller).
    pub affected_contract: String,
    /// The underlying finding from the callee's own analysis.
    #[serde(flatten)]
    pub finding: Finding,
    /// How many dependency hops separate `affected_contract` from `changed_contract`.
    /// 1 = direct dependency, 2+ = transitive.
    pub propagation_depth: usize,
}

// ── Dependency graph ─────────────────────────────────────────────────────────

/// The set of all inter-contract edges declared for a batch run.
///
/// Build once with [`DependencyGraph::from_declarations`], then call
/// [`DependencyGraph::propagate`] after the individual pair analyses have run.
#[derive(Debug, Default, Clone)]
pub struct DependencyGraph {
    /// Edges: caller → list of (callee, watched_functions).
    /// Using BTreeMap for deterministic iteration order.
    edges: BTreeMap<String, Vec<(String, Vec<String>)>>,
    /// All contract names that appear in any edge (as caller or callee).
    pub all_referenced: BTreeSet<String>,
}

impl DependencyGraph {
    /// Build the graph from a list of [`ContractDependency`] declarations.
    ///
    /// Repeated declarations of the same `caller` → `callee` pair are merged
    /// into a single edge rather than stored as separate entries, so cycle
    /// detection and propagation each see exactly one edge per pair. Watched
    /// function lists are unioned; if either declaration watches all
    /// functions (an empty list), the merged edge does too.
    pub fn from_declarations(deps: &[ContractDependency]) -> Self {
        let mut graph = Self::default();
        for dep in deps {
            graph.all_referenced.insert(dep.caller.clone());
            graph.all_referenced.insert(dep.callee.clone());

            let caller_edges = graph.edges.entry(dep.caller.clone()).or_default();
            match caller_edges
                .iter_mut()
                .find(|(callee, _)| *callee == dep.callee)
            {
                Some((_, functions)) => {
                    if functions.is_empty() || dep.functions.is_empty() {
                        functions.clear();
                    } else {
                        for f in &dep.functions {
                            if !functions.contains(f) {
                                functions.push(f.clone());
                            }
                        }
                    }
                }
                None => caller_edges.push((dep.callee.clone(), dep.functions.clone())),
            }
        }
        graph
    }

    /// Return names referenced in dependencies but absent from `known_contracts`.
    ///
    /// These are reported as findings so an operator knows the dependency graph
    /// is incomplete for those edges.
    pub fn missing_contracts<'a>(&'a self, known_contracts: &'a HashSet<String>) -> Vec<&'a str> {
        self.all_referenced
            .iter()
            .filter(|name| !known_contracts.contains(*name))
            .map(String::as_str)
            .collect()
    }

    /// Detect cycles in the dependency graph.
    ///
    /// Returns every cycle as an ordered list of contract names (the path that
    /// forms the cycle, with the first and last element being the same contract).
    /// An empty return means the graph is acyclic.
    pub fn detect_cycles(&self) -> Vec<Vec<String>> {
        let mut visited: HashSet<String> = HashSet::new();
        let mut on_stack: HashSet<String> = HashSet::new();
        let mut cycles: Vec<Vec<String>> = Vec::new();
        let mut path: Vec<String> = Vec::new();

        let nodes: Vec<String> = self.edges.keys().cloned().collect();
        for node in nodes {
            if !visited.contains(&node) {
                self.dfs_cycles(&node, &mut visited, &mut on_stack, &mut path, &mut cycles);
            }
        }
        cycles
    }

    fn dfs_cycles(
        &self,
        node: &str,
        visited: &mut HashSet<String>,
        on_stack: &mut HashSet<String>,
        path: &mut Vec<String>,
        cycles: &mut Vec<Vec<String>>,
    ) {
        visited.insert(node.to_string());
        on_stack.insert(node.to_string());
        path.push(node.to_string());

        if let Some(neighbors) = self.edges.get(node) {
            for (callee, _) in neighbors {
                if !visited.contains(callee) {
                    self.dfs_cycles(callee, visited, on_stack, path, cycles);
                } else if on_stack.contains(callee) {
                    // Found a cycle — extract the path from `callee` to here
                    let cycle_start = path.iter().position(|n| n == callee).unwrap_or(0);
                    let mut cycle: Vec<String> = path[cycle_start..].to_vec();
                    cycle.push(callee.clone()); // close the loop
                    cycles.push(cycle);
                }
            }
        }

        path.pop();
        on_stack.remove(node);
    }

    /// Propagate caller-visible breaking changes from callees to their callers.
    ///
    /// For each contract in `contract_findings`, if it has callers that depend on
    /// it, any finding that is caller-visible (i.e. relates to the exported
    /// interface: function removals, signature changes, parameter changes, return
    /// type changes) is propagated to those callers as a [`CrossContractFinding`].
    ///
    /// Propagation is transitive: if A calls B which calls C, and C breaks, the
    /// break propagates B→A as well. The BFS terminates when no new contracts are
    /// reached. Cycles are handled by tracking which (contract, finding_key) pairs
    /// have already been propagated — a cycle generates exactly one finding per
    /// affected contract per root breaking change, then stops.
    ///
    /// `contract_findings` maps contract name → list of findings from that contract's
    /// own analysis. Only caller-visible findings (by category) are propagated.
    pub fn propagate(
        &self,
        contract_findings: &HashMap<String, Vec<Finding>>,
    ) -> Vec<CrossContractFinding> {
        // Build a reverse map: callee → list of (caller, watched_functions)
        let mut callee_to_callers: BTreeMap<String, Vec<(String, Vec<String>)>> = BTreeMap::new();
        for (caller, edges) in &self.edges {
            for (callee, funcs) in edges {
                callee_to_callers
                    .entry(callee.clone())
                    .or_default()
                    .push((caller.clone(), funcs.clone()));
            }
        }

        let mut result: Vec<CrossContractFinding> = Vec::new();
        // Track (affected_contract, changed_contract, finding_key) to prevent
        // duplicate findings and to terminate cycles.
        let mut emitted: HashSet<(String, String, String)> = HashSet::new();

        // Seed the BFS with caller-visible findings from each callee.
        // Queue entries: (changed_contract, affected_contract, finding, depth)
        let mut queue: VecDeque<(String, String, Finding, usize)> = VecDeque::new();

        for (callee, findings) in contract_findings {
            for finding in findings {
                if !is_caller_visible(finding) {
                    continue;
                }
                if let Some(callers) = callee_to_callers.get(callee) {
                    for (caller, watched_fns) in callers {
                        if !function_is_watched(finding, watched_fns) {
                            continue;
                        }
                        let key = propagation_key(callee, finding);
                        let dedup = (caller.clone(), callee.clone(), key);
                        if emitted.insert(dedup) {
                            queue.push_back((callee.clone(), caller.clone(), finding.clone(), 1));
                        }
                    }
                }
            }
        }

        // BFS: propagate transitively, one hop at a time.
        while let Some((changed, affected, finding, depth)) = queue.pop_front() {
            result.push(CrossContractFinding {
                changed_contract: changed.clone(),
                affected_contract: affected.clone(),
                finding: finding.clone(),
                propagation_depth: depth,
            });

            // Now propagate from `affected` to its own callers.
            if let Some(callers_of_affected) = callee_to_callers.get(&affected) {
                for (caller_of_caller, watched_fns) in callers_of_affected {
                    if !function_is_watched(&finding, watched_fns) {
                        continue;
                    }
                    let key = propagation_key(&changed, &finding);
                    let dedup = (caller_of_caller.clone(), changed.clone(), key);
                    if emitted.insert(dedup) {
                        queue.push_back((
                            changed.clone(),
                            caller_of_caller.clone(),
                            finding.clone(),
                            depth + 1,
                        ));
                    }
                }
            }
        }

        // Sort for determinism: by depth, then changed, then affected, then target.
        result.sort_by(|a, b| {
            a.propagation_depth
                .cmp(&b.propagation_depth)
                .then_with(|| a.changed_contract.cmp(&b.changed_contract))
                .then_with(|| a.affected_contract.cmp(&b.affected_contract))
                .then_with(|| a.finding.target.cmp(&b.finding.target))
        });

        result
    }
}

// ── Propagation helpers ──────────────────────────────────────────────────────

/// Categories that are visible to a cross-contract caller.
///
/// Storage, documentation, and info findings are internal to a contract and
/// irrelevant to callers. A caller cares about what it can *call*: function
/// presence, parameter shapes, return types, and cascading type breaks (which
/// can change the types a function accepts or returns).
const CALLER_VISIBLE_CATEGORIES: &[&str] = &[
    "Function Removed",
    "Function Signature Changed",
    "Parameter Renamed",
    "Parameter Reordered",
    "Parameter Type Changed",
    "Return Type Changed",
    "Struct Removed",
    "Struct Field Removed",
    "Struct Field Reordered",
    "Struct Field Type Changed",
    "Struct Field Inserted",
    "Enum Removed",
    "Enum Case Removed",
    "Enum Case Value Changed",
    "Union Removed",
    "Union Case Removed",
    "Union Case Reordered",
    "Union Case Type Changed",
    "Union Case Inserted",
    "Error Enum Removed",
    "Error Enum Case Removed",
    "Error Enum Case Value Changed",
    "Cascading Layout Break",
];

/// Whether a finding is visible to contracts that call the changed contract.
///
/// We propagate `Critical` and `Warning` findings only — `Info` findings like
/// "Function Added" or "Enum Case Added" are not breaking for a caller.
pub fn is_caller_visible(finding: &Finding) -> bool {
    if finding.severity == Severity::Info {
        return false;
    }
    CALLER_VISIBLE_CATEGORIES
        .iter()
        .any(|&cat| finding.category == cat)
}

/// Whether the finding relates to a function the caller explicitly listed.
///
/// When `watched_fns` is empty the caller depends on the whole interface, so
/// every caller-visible finding passes. When it is non-empty only findings
/// whose `target` starts with one of the watched function names pass.
fn function_is_watched(finding: &Finding, watched_fns: &[String]) -> bool {
    if watched_fns.is_empty() {
        return true;
    }
    let target = match finding.target.as_deref() {
        Some(t) => t,
        // Targetless findings (e.g. environment metadata) are always considered
        // relevant when no function filter is set; with a filter, skip them
        // since they do not belong to any specific function.
        None => return false,
    };
    watched_fns
        .iter()
        .any(|fn_name| target == fn_name.as_str() || target.starts_with(&format!("{}.", fn_name)))
}

/// A stable string key for a finding used to deduplicate propagated copies.
fn propagation_key(contract: &str, finding: &Finding) -> String {
    format!(
        "{}|{}|{}",
        contract,
        finding.category,
        finding.target.as_deref().unwrap_or("")
    )
}

// ── Cycle and missing-contract findings ─────────────────────────────────────

/// Build findings for cyclic dependencies.
///
/// A cycle is not automatically an error — the contracts can still be analyzed
/// individually — but it must be reported clearly so an operator knows the
/// upgrade ordering matters.
pub fn cycle_findings(cycles: &[Vec<String>]) -> Vec<Finding> {
    cycles
        .iter()
        .map(|cycle| {
            let path = cycle.join(" → ");
            Finding {
                axes: Vec::new(),
                severity: Severity::Warning,
                category: "Cyclic Contract Dependency".to_string(),
                message: format!(
                    "Cyclic dependency detected: {}. \
                     Upgrade order matters — deploying these contracts in the wrong order \
                     may leave the protocol in an inconsistent state.",
                    path
                ),
                type_name: None,
                target: Some(cycle[0].clone()),
                change: None,
                root_target: None,
            }
        })
        .collect()
}

/// Build findings for dependencies on contracts absent from the batch.
///
/// When a declared callee is not present in the batch, the safety of its callers
/// cannot be verified. This is reported at `Warning` severity — the analysis of
/// the caller still runs, but its verdict is incomplete.
pub fn missing_contract_findings(missing: &[&str]) -> Vec<Finding> {
    missing
        .iter()
        .map(|name| Finding {
            axes: Vec::new(),
            severity: Severity::Warning,
            category: "Missing Dependency Contract".to_string(),
            message: format!(
                "Contract '{}' is declared as a dependency but is not present in this batch run. \
                 The safety of contracts that depend on '{}' cannot be fully verified.",
                name, name
            ),
            type_name: None,
            target: Some(name.to_string()),
            change: None,
            root_target: None,
        })
        .collect()
}

// ── Tests ───────────────────────────────────────────────────────────────────

#[cfg(test)]
mod tests {
    use super::*;
    use crate::diff::Severity;

    fn dep(caller: &str, callee: &str) -> ContractDependency {
        ContractDependency {
            caller: caller.to_string(),
            callee: callee.to_string(),
            functions: vec![],
        }
    }

    fn dep_filtered(caller: &str, callee: &str, fns: &[&str]) -> ContractDependency {
        ContractDependency {
            caller: caller.to_string(),
            callee: callee.to_string(),
            functions: fns.iter().map(|s| s.to_string()).collect(),
        }
    }

    fn critical_finding(category: &str, target: &str) -> Finding {
        Finding {
            severity: Severity::Critical,
            axes: Vec::new(),
            category: category.to_string(),
            message: format!("Breaking change in {}", target),
            type_name: None,
            target: Some(target.to_string()),
            change: None,
            root_target: None,
        }
    }

    fn warning_finding(category: &str, target: &str) -> Finding {
        Finding {
            severity: Severity::Warning,
            axes: Vec::new(),
            category: category.to_string(),
            message: format!("Warning change in {}", target),
            type_name: None,
            target: Some(target.to_string()),
            change: None,
            root_target: None,
        }
    }

    fn info_finding(category: &str, target: &str) -> Finding {
        Finding {
            severity: Severity::Info,
            axes: Vec::new(),
            category: category.to_string(),
            message: format!("Info change in {}", target),
            type_name: None,
            target: Some(target.to_string()),
            change: None,
            root_target: None,
        }
    }

    // ── is_caller_visible ────────────────────────────────────────────────────

    #[test]
    fn function_removed_is_caller_visible() {
        let f = critical_finding("Function Removed", "transfer");
        assert!(is_caller_visible(&f));
    }

    #[test]
    fn parameter_type_changed_is_caller_visible() {
        let f = critical_finding("Parameter Type Changed", "transfer.amount");
        assert!(is_caller_visible(&f));
    }

    #[test]
    fn function_added_info_is_not_caller_visible() {
        let f = info_finding("Function Added", "new_fn");
        assert!(!is_caller_visible(&f));
    }

    #[test]
    fn struct_added_info_is_not_caller_visible() {
        let f = info_finding("Struct Added", "NewStruct");
        assert!(!is_caller_visible(&f));
    }

    #[test]
    fn warning_parameter_renamed_is_caller_visible() {
        let f = warning_finding("Parameter Renamed", "transfer.from");
        assert!(is_caller_visible(&f));
    }

    #[test]
    fn environment_finding_not_propagated() {
        // Environment is not in CALLER_VISIBLE_CATEGORIES
        let f = warning_finding("Environment", "");
        assert!(!is_caller_visible(&f));
    }

    // ── Direct propagation ───────────────────────────────────────────────────

    #[test]
    fn direct_dependency_propagates_critical() {
        let graph = DependencyGraph::from_declarations(&[dep("pool", "token")]);

        let mut findings: HashMap<String, Vec<Finding>> = HashMap::new();
        findings.insert(
            "token".to_string(),
            vec![critical_finding("Function Removed", "transfer")],
        );

        let cross = graph.propagate(&findings);
        assert_eq!(cross.len(), 1);
        assert_eq!(cross[0].changed_contract, "token");
        assert_eq!(cross[0].affected_contract, "pool");
        assert_eq!(cross[0].finding.category, "Function Removed");
        assert_eq!(cross[0].propagation_depth, 1);
    }

    #[test]
    fn no_findings_produces_no_cross_contract_findings() {
        let graph = DependencyGraph::from_declarations(&[dep("pool", "token")]);
        let findings: HashMap<String, Vec<Finding>> = HashMap::new();
        let cross = graph.propagate(&findings);
        assert!(cross.is_empty());
    }

    #[test]
    fn info_findings_do_not_propagate() {
        let graph = DependencyGraph::from_declarations(&[dep("pool", "token")]);
        let mut findings: HashMap<String, Vec<Finding>> = HashMap::new();
        findings.insert(
            "token".to_string(),
            vec![info_finding("Function Added", "new_fn")],
        );
        let cross = graph.propagate(&findings);
        assert!(
            cross.is_empty(),
            "Info findings must not propagate to callers"
        );
    }

    #[test]
    fn no_dependency_means_no_propagation() {
        let graph = DependencyGraph::from_declarations(&[]);
        let mut findings: HashMap<String, Vec<Finding>> = HashMap::new();
        findings.insert(
            "token".to_string(),
            vec![critical_finding("Function Removed", "transfer")],
        );
        let cross = graph.propagate(&findings);
        assert!(cross.is_empty());
    }

    // ── Function filter ──────────────────────────────────────────────────────

    #[test]
    fn watched_function_propagates() {
        let graph =
            DependencyGraph::from_declarations(&[dep_filtered("pool", "token", &["transfer"])]);
        let mut findings: HashMap<String, Vec<Finding>> = HashMap::new();
        findings.insert(
            "token".to_string(),
            vec![critical_finding("Function Removed", "transfer")],
        );
        let cross = graph.propagate(&findings);
        assert_eq!(cross.len(), 1);
    }

    #[test]
    fn unwatched_function_does_not_propagate() {
        let graph =
            DependencyGraph::from_declarations(&[dep_filtered("pool", "token", &["balance"])]);
        let mut findings: HashMap<String, Vec<Finding>> = HashMap::new();
        findings.insert(
            "token".to_string(),
            vec![critical_finding("Function Removed", "transfer")],
        );
        let cross = graph.propagate(&findings);
        assert!(
            cross.is_empty(),
            "Finding for unwatched function must not propagate"
        );
    }

    #[test]
    fn parameter_finding_matches_function_prefix() {
        // "transfer.amount" starts with "transfer." so it matches the filter
        let graph =
            DependencyGraph::from_declarations(&[dep_filtered("pool", "token", &["transfer"])]);
        let mut findings: HashMap<String, Vec<Finding>> = HashMap::new();
        findings.insert(
            "token".to_string(),
            vec![critical_finding(
                "Parameter Type Changed",
                "transfer.amount",
            )],
        );
        let cross = graph.propagate(&findings);
        assert_eq!(cross.len(), 1);
    }

    // ── Transitive propagation ───────────────────────────────────────────────

    #[test]
    fn transitive_propagation_reaches_indirect_caller() {
        // router → pool → token
        let graph =
            DependencyGraph::from_declarations(&[dep("pool", "token"), dep("router", "pool")]);
        let mut findings: HashMap<String, Vec<Finding>> = HashMap::new();
        findings.insert(
            "token".to_string(),
            vec![critical_finding("Function Removed", "transfer")],
        );
        let cross = graph.propagate(&findings);

        let pool_findings: Vec<_> = cross
            .iter()
            .filter(|f| f.affected_contract == "pool")
            .collect();
        let router_findings: Vec<_> = cross
            .iter()
            .filter(|f| f.affected_contract == "router")
            .collect();

        assert!(!pool_findings.is_empty(), "pool must receive a finding");
        assert!(!router_findings.is_empty(), "router must receive a finding");
        assert_eq!(pool_findings[0].propagation_depth, 1);
        assert_eq!(router_findings[0].propagation_depth, 2);
    }

    // ── Cyclic dependency ────────────────────────────────────────────────────

    #[test]
    fn cyclic_dependency_terminates() {
        // A → B → A (mutual dependency)
        let graph = DependencyGraph::from_declarations(&[dep("A", "B"), dep("B", "A")]);
        let mut findings: HashMap<String, Vec<Finding>> = HashMap::new();
        findings.insert(
            "A".to_string(),
            vec![critical_finding("Function Removed", "fn_a")],
        );
        findings.insert(
            "B".to_string(),
            vec![critical_finding("Function Removed", "fn_b")],
        );
        // Must terminate without infinite loop
        let cross = graph.propagate(&findings);
        // Each contract gets exactly one finding from the other, no duplicates
        let b_affected: Vec<_> = cross
            .iter()
            .filter(|f| f.affected_contract == "B")
            .collect();
        let a_affected: Vec<_> = cross
            .iter()
            .filter(|f| f.affected_contract == "A")
            .collect();
        // Each should get findings, but no unbounded growth
        assert!(
            cross.len() <= 4,
            "cycle must not produce unbounded findings"
        );
        // Both contracts must be affected
        assert!(!b_affected.is_empty());
        assert!(!a_affected.is_empty());
    }

    #[test]
    fn cycle_detection_finds_simple_cycle() {
        let graph = DependencyGraph::from_declarations(&[dep("A", "B"), dep("B", "A")]);
        let cycles = graph.detect_cycles();
        assert!(!cycles.is_empty(), "must detect the A→B→A cycle");
    }

    #[test]
    fn acyclic_graph_has_no_cycles() {
        let graph =
            DependencyGraph::from_declarations(&[dep("pool", "token"), dep("router", "pool")]);
        let cycles = graph.detect_cycles();
        assert!(cycles.is_empty(), "acyclic graph must have no cycles");
    }

    // ── Duplicate edge declarations ──────────────────────────────────────────

    #[test]
    fn repeated_declaration_produces_one_edge_not_two() {
        let graph =
            DependencyGraph::from_declarations(&[dep("pool", "token"), dep("pool", "token")]);

        let mut findings: HashMap<String, Vec<Finding>> = HashMap::new();
        findings.insert(
            "token".to_string(),
            vec![critical_finding("Function Removed", "transfer")],
        );

        let cross = graph.propagate(&findings);
        assert_eq!(
            cross.len(),
            1,
            "a callee declared twice by the same caller must still produce one finding"
        );
    }

    #[test]
    fn repeated_edge_in_a_cycle_is_not_reported_twice() {
        // "B" declares its dependency on "A" twice; the cycle it forms with
        // "A" → "B" must still be reported once, not once per duplicate edge.
        let graph =
            DependencyGraph::from_declarations(&[dep("A", "B"), dep("B", "A"), dep("B", "A")]);
        let cycles = graph.detect_cycles();
        assert_eq!(
            cycles.len(),
            1,
            "a duplicated back-edge must not multiply the reported cycle, got {:?}",
            cycles
        );
    }

    #[test]
    fn distinct_callees_from_the_same_caller_remain_independent() {
        let graph =
            DependencyGraph::from_declarations(&[dep("router", "pool"), dep("router", "token")]);

        let mut findings: HashMap<String, Vec<Finding>> = HashMap::new();
        findings.insert(
            "pool".to_string(),
            vec![critical_finding("Function Removed", "swap")],
        );
        findings.insert(
            "token".to_string(),
            vec![critical_finding("Function Removed", "transfer")],
        );

        let cross = graph.propagate(&findings);
        assert_eq!(
            cross.len(),
            2,
            "distinct caller-callee edges must not be collapsed into one"
        );
    }

    #[test]
    fn merging_a_filtered_and_unfiltered_declaration_watches_all_functions() {
        // One declaration watches only "transfer"; a second, redundant
        // declaration for the same pair watches everything. The merged edge
        // must watch everything — the narrower filter must not win.
        let graph = DependencyGraph::from_declarations(&[
            dep_filtered("pool", "token", &["transfer"]),
            dep("pool", "token"),
        ]);

        let mut findings: HashMap<String, Vec<Finding>> = HashMap::new();
        findings.insert(
            "token".to_string(),
            vec![critical_finding("Function Removed", "burn")],
        );

        let cross = graph.propagate(&findings);
        assert_eq!(
            cross.len(),
            1,
            "merged edge must watch all functions once any declaration has no filter"
        );
    }

    #[test]
    fn merging_two_filtered_declarations_unions_watched_functions() {
        let graph = DependencyGraph::from_declarations(&[
            dep_filtered("pool", "token", &["transfer"]),
            dep_filtered("pool", "token", &["balance"]),
        ]);

        let mut findings: HashMap<String, Vec<Finding>> = HashMap::new();
        findings.insert(
            "token".to_string(),
            vec![
                critical_finding("Function Removed", "transfer"),
                critical_finding("Function Removed", "balance"),
                critical_finding("Function Removed", "burn"),
            ],
        );

        let cross = graph.propagate(&findings);
        let targets: HashSet<&str> = cross
            .iter()
            .map(|c| c.finding.target.as_deref().unwrap_or(""))
            .collect();
        assert_eq!(
            targets,
            ["transfer", "balance"].into_iter().collect(),
            "the union of both declarations' watched functions must be honored, and burn (watched by neither) excluded"
        );
    }

    // ── Missing contracts ────────────────────────────────────────────────────

    #[test]
    fn missing_callee_is_reported() {
        let graph = DependencyGraph::from_declarations(&[dep("pool", "oracle")]);
        let known: HashSet<String> = ["pool".to_string()].into_iter().collect();
        let missing = graph.missing_contracts(&known);
        assert_eq!(missing, vec!["oracle"]);
    }

    #[test]
    fn all_present_reports_nothing_missing() {
        let graph = DependencyGraph::from_declarations(&[dep("pool", "token")]);
        let known: HashSet<String> = ["pool".to_string(), "token".to_string()]
            .into_iter()
            .collect();
        let missing = graph.missing_contracts(&known);
        assert!(missing.is_empty());
    }

    // ── Multiple callers ─────────────────────────────────────────────────────

    #[test]
    fn multiple_callers_all_receive_findings() {
        // Both pool and router call token.
        let graph =
            DependencyGraph::from_declarations(&[dep("pool", "token"), dep("router", "token")]);
        let mut findings: HashMap<String, Vec<Finding>> = HashMap::new();
        findings.insert(
            "token".to_string(),
            vec![critical_finding("Function Removed", "transfer")],
        );
        let cross = graph.propagate(&findings);
        let pool_hit = cross.iter().any(|f| f.affected_contract == "pool");
        let router_hit = cross.iter().any(|f| f.affected_contract == "router");
        assert!(pool_hit, "pool must receive the finding");
        assert!(router_hit, "router must receive the finding");
    }

    // ── Warning propagation ──────────────────────────────────────────────────

    #[test]
    fn warning_findings_propagate_to_callers() {
        let graph = DependencyGraph::from_declarations(&[dep("pool", "token")]);
        let mut findings: HashMap<String, Vec<Finding>> = HashMap::new();
        findings.insert(
            "token".to_string(),
            vec![warning_finding("Parameter Renamed", "transfer.from")],
        );
        let cross = graph.propagate(&findings);
        assert!(!cross.is_empty(), "Warning findings must propagate");
        assert_eq!(cross[0].finding.severity, Severity::Warning);
    }

    // ── Cycle findings and missing contract findings ─────────────────────────

    #[test]
    fn cycle_findings_describe_the_cycle() {
        let cycles = vec![vec!["A".to_string(), "B".to_string(), "A".to_string()]];
        let findings = cycle_findings(&cycles);
        assert_eq!(findings.len(), 1);
        assert_eq!(findings[0].category, "Cyclic Contract Dependency");
        assert_eq!(findings[0].severity, Severity::Warning);
        assert!(findings[0].message.contains("A → B → A"));
    }

    #[test]
    fn missing_contract_findings_describe_the_absent_contract() {
        let findings = missing_contract_findings(&["oracle"]);
        assert_eq!(findings.len(), 1);
        assert_eq!(findings[0].category, "Missing Dependency Contract");
        assert_eq!(findings[0].severity, Severity::Warning);
        assert!(findings[0].message.contains("oracle"));
    }
}
