// SPDX-License-Identifier: MIT

//! JSON Schema generation for the report document.
//!
//! The report shape produced by `--format json` is described by a JSON Schema
//! that tooling can fetch with the `print-schema` subcommand, without running
//! a comparison or locating a file in the repository.
//!
//! The schema is generated by [`schemars`] from the same `serde` types that
//! produce the actual reports, so it cannot drift from what the running binary
//! really emits: any change to a `serde` attribute on a field of
//! [`crate::render::RenderableReport`] (or a type it embeds) shows up here
//! automatically.

use crate::impact_graph::ImpactGraph;
use crate::render::RenderableReport;

/// Build the JSON Schema document that describes every report shape this
/// build of the binary can emit.
///
/// The returned schema is self-contained — every definition is inlined into
/// the document, so consumers can pipe it straight into a validator without
/// resolving external references. Centralized here so the schema stays next
/// to the rest of the report model rather than buried in CLI plumbing.
pub fn report_schema() -> schemars::schema::RootSchema {
    schemars::schema_for!(RenderableReport)
}

/// Serialize [`report_schema`] to a `serde_json::Value`. Pure helper, kept
/// separate from any I/O so it can be unit-tested.
pub fn report_schema_value() -> serde_json::Value {
    let schema = report_schema();
    serde_json::to_value(&schema).expect("JSON Schema serialization is infallible")
}

/// Build the JSON Schema document for the `impact_graph` field's shape
/// (see `crate::impact_graph`), standalone rather than as a `RenderableReport`
/// subschema — so a consumer that only wants to validate `--impact-graph-file`
/// output doesn't need to pull in the whole report schema.
pub fn impact_graph_schema() -> schemars::schema::RootSchema {
    schemars::schema_for!(ImpactGraph)
}

/// Serialize [`impact_graph_schema`] to a `serde_json::Value`.
pub fn impact_graph_schema_value() -> serde_json::Value {
    let schema = impact_graph_schema();
    serde_json::to_value(&schema).expect("JSON Schema serialization is infallible")
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn schema_is_valid_json_with_required_top_level_fields() {
        let value = report_schema_value();
        let obj = value.as_object().expect("schema is a JSON object");
        assert_eq!(
            obj.get("$schema").and_then(|v| v.as_str()),
            Some("http://json-schema.org/draft-07/schema#")
        );
        let props = obj.get("properties").and_then(|v| v.as_object()).unwrap();
        for field in [
            "report_schema_version",
            "provenance",
            "is_safe",
            "counts",
            "findings_by_category",
        ] {
            assert!(props.contains_key(field), "schema missing `{field}`");
        }
    }
}
